### ISSUE TITLE
Features suggestion

### ISSUE THREAD

**Issue by fmonet** [firefart/gochro#16]
Hi,

It's a great job you've done.
Some feature suggestions that might be great to implement in the future:

1. Argument to ignore cookies: to avoid GDPR popups
2. Argument to specify the browser language (Accept-Language) in the request
3. Export as a PNG 
4. Argument to set the user agent

Cheers,

**Comment by firefart** [comment]
Hi,
thanks for your suggestion

1) this is not possible. GDPR popups work by setting a specific cookie to a value. You can't ignore them without knowing the cookie names and values
2) this does not seem to be possible because chrome does not support this via it's command line arguments
3) the screenshots are already exported as png
4) this is possible, will look into it

**Comment by firefart** [comment]
you can now set the useragent with the `useragent=xxxx` get parameter on both endpoints
